### ISSUE TITLE
程式執行錯誤

### ISSUE THREAD

**Issue by YuSiang1** [jing-tw/climbing#10]
您好，主程式執行後發生以下錯誤，請問要如何解決，謝謝。
(venv_climbing) C:\autoclimb-master>python autoclimb.py
checking version ...
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "autoclimb.py", line 240, in __check_update__
    subprocess.check_output('git fetch'.split())  # update ref
  File "C:\Users\YSH\Anaconda3\envs\venv_climbing\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "C:\Users\YSH\Anaconda3\envs\venv_climbing\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'fetch']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "autoclimb.py", line 89, in __check_version__
    _, desc, local_id = __check_update__()
  File "autoclimb.py", line 261, in __check_update__
    return 4, desc, local
UnboundLocalError: local variable 'local' referenced before assignment

(venv_climbing) C:\autoclimb-master>

**Comment by jing-tw** [comment]
Hi,
根據錯誤訊息 fatal: not a git repository (or any of the parent directories): .git
表示你的目錄沒有 .git 目錄.
導致這個問題發生.

這個程式使用 git 進行版本檢查, 以確保程式維持最新版本狀態.
所以作法為:

還是得從 github 把程式抓下來, 安裝與執行
https://github.com/jing-tw/autoclimb#%E5%AE%89%E8%A3%9D%E7%92%B0%E5%A2%83


Jing.
