### ISSUE TITLE
兩個選項未勾選，之後停止自動填寫

### ISSUE THREAD

**Issue by Uzi-Wang** [jing-tw/climbing#11]
checking version ...
雪霸國家公園
load
C:/Users/uzimi/autoclimb/sample_9_people.xlsx
read file  C:/Users/uzimi/autoclimb/sample_9_people.xlsx
資料檔格式資訊
        version : v0.0.1
Start Taiwan National Park Automation

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 103.0.5060
[WDM] - Get LATEST chromedriver version for 103.0.5060 google-chrome
[WDM] - There is no [win32] chromedriver for browser 103.0.5060 in cache
[WDM] - About to download new driver from https://chromedriver.storage.googleapis.com/103.0.5060.53/chromedriver_win32.zip
[WDM] - Driver has been saved in cache [C:\Users\uzimi\.wdm\drivers\chromedriver\win32\103.0.5060.53]

DevTools listening on ws://127.0.0.1:55401/devtools/browser/177b8006-6cd1-4107-abf0-da3a40e00f26
[15076:10228:0629/023654.206:ERROR:device_event_log_impl.cc(214)] [02:36:54.205] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: 連結到系統的某個裝置失去作用。 (0x1F)
[15076:10228:0629/023654.212:ERROR:device_event_log_impl.cc(214)] [02:36:54.211] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: 連結到系統的某個裝置失去作用。 (0x1F)
Traceback (most recent call last):
  File "autoclimb.py", line 168, in run
    self.obj_auto.run()
  File "C:\Users\uzimi\autoclimb\park_auto.py", line 85, in run
    switch[self.park]()
  File "C:\Users\uzimi\autoclimb\park_auto.py", line 142, in __run__sheipa__
    self.__apply__()
  File "C:\Users\uzimi\autoclimb\park_auto.py", line 101, in __apply__
    self.__fill_form_schedule__(EnumTabID.id_tab_schedule)
  File "C:\Users\uzimi\autoclimb\park_auto.py", line 148, in __fill_form_schedule__
    self.browser.fill_text('ContentPlaceHolder1_teams_name', dict_team['name'] + datetime.now().strftime("%Y%m%d%H%M%S"), 0) # 隊名
  File "C:\Users\uzimi\autoclimb\browser_auto.py", line 154, in fill_text
    return self.__fill_text_core__('fill_text', str_id, str_text, b_refilled)
  File "C:\Users\uzimi\autoclimb\browser_auto.py", line 173, in __fill_text_core__
    return self.__do_action__(str_fun_name, dict_arg)
  File "C:\Users\uzimi\autoclimb\browser_auto.py", line 74, in __do_action__
    b_ok, msg = self.__switch__(str_cmd, dict_arg)
  File "C:\Users\uzimi\autoclimb\browser_auto.py", line 94, in __switch__
    return fun_switch[str_cmd](dict_arg)
  File "C:\Users\uzimi\autoclimb\browser_auto.py", line 179, in __fill_text__
    element = self._get_elm_id(str_id)
  File "C:\Users\uzimi\autoclimb\browser_auto.py", line 276, in _get_elm_id
    EC.element_to_be_clickable((By.ID, str_id))
  File "C:\Users\uzimi\anaconda3\envs\venv_climbing\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\uzimi\anaconda3\envs\venv_climbing\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 297, in __call__
    element = visibility_of_element_located(self.locator)(driver)
  File "C:\Users\uzimi\anaconda3\envs\venv_climbing\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Users\uzimi\anaconda3\envs\venv_climbing\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Users\uzimi\anaconda3\envs\venv_climbing\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Users\uzimi\anaconda3\envs\venv_climbing\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\uzimi\anaconda3\envs\venv_climbing\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\uzimi\anaconda3\envs\venv_climbing\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 尚有2項同意事項未勾選
Message: unexpected alert open: {Alert text : 尚有2項同意事項未勾選}
  (Session info: chrome=103.0.5060.66)

查閱上方錯誤訊息, 進行檢測.

1.請確定你的機器是否連上網際網路
2.瀏覽器是否已經被關閉了
3.有可能是瀏覽器版本太舊了, 請更新你的瀏覽器版本.
4.若前面都檢查過, 那可能是其他問題, 請複製上方錯誤資訊 call stack 發出 error issue 到 github.

Detail:Alert Text: 尚有2項同意事項未勾選
Message: unexpected alert open: {Alert text : 尚有2項同意事項未勾選}
  (Session info: chrome=103.0.5060.66)

更新 Chrome 最新版本的指令:
Ubuntu:
sudo apt-get --only-upgrade install google-chrome-stable

**Comment by RaleighGithub** [comment]
At first, thanks author for your contribution.
But, I have a same problem like above  returns durring operation.
好人一生平安
