### ISSUE TITLE
載入國家公園版本檢查頁面後就crash

### ISSUE THREAD

**Issue by Jake83114** [jing-tw/climbing#12]
首先很感謝作者撰寫這個code供山友們使用，
今天學習這個程式的使用方法，依照readme的步驟操作下來，
順利執行到：
_(venv_climbing) C:\Users\*****\Desktop\autoclimb-master>python autoclimb.py_
程式開啟國家公園的介面後就馬上crash了

crash後的回報如下
_checking version ...
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "autoclimb.py", line 225, in __check_update__
    subprocess.check_output('git fetch'.split())  # update ref
  File "C:\Users\*****\anaconda3\envs\venv_climbing\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "C:\Users\*****\anaconda3\envs\venv_climbing\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'fetch']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "autoclimb.py", line 89, in __check_version__
    ret, desc, local_id = __check_update__()
  File "autoclimb.py", line 246, in __check_update__
    return 4, desc, local
UnboundLocalError: local variable 'local' referenced before assignment_

不知這狀況如何解? 向作者求助，謝謝！

山友 老皮 敬上
eil83114@gmail.com

**Comment by chengnill** [comment]
請問有解嗎?
