### ISSUE TITLE
[issue] 執行主程式發生 OSError: [Errno 26] Text file busy 

### ISSUE THREAD

**Issue by jing-tw** [jing-tw/climbing#9]
執行主程式發生 OSError: [Errno 26] Text file busy

Reproduce Step:
python3 autoclimb.py

--- 詳細 Log ---
(venv_climbing2) > $ python3 autoclimb.py                           [±master ●]
checking version ...
<div align="left"><br>狀態: 目前是最新版.</div><div align="left">版本號碼:489c6a8b4c253d8e33a2ab15e14647eaffc58c93.</div>
雪霸國家公園
load
/home/jing/work/autoclimb/雪山主峰1日攀登計畫_Mike_personal, 3,886.xlsx
read file  /home/jing/work/autoclimb/雪山主峰1日攀登計畫_Mike_personal, 3,886.xlsx
資料檔格式資訊
	version : v0.0.1
reply =  NO
reply =  65536
Start Taiwan National Park Automation 
Trying to download new driver from http://chromedriver.storage.googleapis.com/81.0.4044.138/chromedriver_linux64.zip
Unpack archive /home/jing/.wdm/drivers/chromedriver/81.0.4044.138/linux64/chromedriver.zip
Traceback (most recent call last):
  File "autoclimb.py", line 169, in run
    self.obj_auto.run()
  File "/home/jing/work/autoclimb/park_auto.py", line 81, in run
    self.browser = BrowserAuto(self.addr_park)
  File "/home/jing/work/autoclimb/browser_auto.py", line 30, in __init__
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "/home/jing/anaconda3/envs/venv_climbing2/lib/python3.6/site-packages/webdriver_manager/chrome.py", line 24, in install
    driver_path = self.download_driver(self.driver)
  File "/home/jing/anaconda3/envs/venv_climbing2/lib/python3.6/site-packages/webdriver_manager/manager.py", line 39, in download_driver
    path = self.__download_and_save_driver_to_cache(driver, driver_version)
  File "/home/jing/anaconda3/envs/venv_climbing2/lib/python3.6/site-packages/webdriver_manager/manager.py", line 29, in __download_and_save_driver_to_cache
    driver.get_os_type())
  File "/home/jing/anaconda3/envs/venv_climbing2/lib/python3.6/site-packages/webdriver_manager/driver_cache.py", line 60, in save_driver_to_cache
    files = self.__unpack(file_path)
  File "/home/jing/anaconda3/envs/venv_climbing2/lib/python3.6/site-packages/webdriver_manager/driver_cache.py", line 99, in __unpack
    return extract_zip(path, to_directory)
  File "/home/jing/anaconda3/envs/venv_climbing2/lib/python3.6/site-packages/webdriver_manager/archive.py", line 7, in extract_zip
    archive.extractall(to_directory)
  File "/home/jing/anaconda3/envs/venv_climbing2/lib/python3.6/zipfile.py", line 1524, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/home/jing/anaconda3/envs/venv_climbing2/lib/python3.6/zipfile.py", line 1578, in _extract_member
    open(targetpath, "wb") as target:
OSError: [Errno 26] Text file busy: '/home/jing/.wdm/drivers/chromedriver/81.0.4044.138/linux64/chromedriver'

查閱上方錯誤訊息, 進行檢測.

1.請確定你的機器是否連上網際網路
2.瀏覽器是否已經被關閉了
3.有可能是瀏覽器版本太舊了, 請更新你的瀏覽器版本.

Detail:[Errno 26] Text file busy: '/home/jing/.wdm/drivers/chromedriver/81.0.4044.138/linux64/chromedriver'
更新 Chrome 最新版本的指令:
Ubuntu:
sudo apt-get --only-upgrade install google-chrome-stable

**Comment by jing-tw** [comment]
Root Cause: 
這是因為之前執行開啟的 Chrome 沒有關掉, 導致 chromedriver locked.

Resolve:
關閉之前開啟的 Chrome.

for Liunx
$ pidof chrome 
$ pkill -f chrome
